name: movikoox
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  universal_io: ^2.2.2
  http: ^1.2.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  go_router: ^13.0.1
  flutter_riverpod: ^2.4.0
  flutter_svg: ^2.0.9
  modal_bottom_sheet: ^3.0.0
  permission_handler: ^11.1.0
  animations: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

# CONFIGURACIÓN DE ICONOS DE LA APLICACIÓN
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/icons/movikoox_icon.png"
    background_color: "#922E42"
    theme_color: "#922E42"
  image_path: "assets/icons/movikoox_icon.png"
  # Configuración para iconos adaptativos de Android (8.0+)
  adaptive_icon_background: "#922E42"
  adaptive_icon_foreground: "assets/icons/movikoox_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/